"""Build a normalised ``standard_prd`` from static analysis (ZERO tier).

Deterministic: groups endpoints/pages into features and renders human-readable
user-flows. An LLM enrichment pass (CLOUD/LOCAL tier) can later rewrite the prose
via ``packages/agent``; this baseline never requires a model.
"""

from __future__ import annotations

from suitest_lifecycle.models import CodeSummary, Endpoint, Mode, Prd, PrdFeature


def _title(slug: str) -> str:
    return slug.replace("-", " ").replace("_", " ").strip().title() or "Root"


def _backend_features(summary: CodeSummary) -> list[PrdFeature]:
    by_group: dict[str, list[Endpoint]] = {}
    for ep in summary.endpoints:
        parts = [
            p for p in ep.path.strip("/").split("/") if p and not p.startswith(":") and p != "api"
        ]
        key = parts[0] if parts else "root"
        by_group.setdefault(key, []).append(ep)

    features: list[PrdFeature] = []
    for group, eps in sorted(by_group.items()):
        flows: list[str] = []
        for ep in eps:
            auth = " (auth required)" if ep.auth_required else " (public)"
            flows.append(f"{ep.method} {ep.path}{auth} -> expected 2xx for valid input")
        features.append(
            PrdFeature(
                name=_title(group),
                description=f"{group} API surface ({len(eps)} endpoint(s)).",
                user_flows=flows,
            )
        )
    return features


def _frontend_features(summary: CodeSummary) -> list[PrdFeature]:
    features: list[PrdFeature] = []
    for page in summary.pages:
        guard = " (protected)" if page.protected else " (public)"
        features.append(
            PrdFeature(
                name=page.name,
                description=f"Page at route {page.route}{guard}.",
                user_flows=[f"Navigate to {page.route} -> page renders without error"],
            )
        )
    return features


def build_prd(summary: CodeSummary, date: str, project: str) -> Prd:
    if summary.mode is Mode.BACKEND:
        overview = (
            f"{project} is a {', '.join(summary.tech_stack)} backend exposing "
            f"{len(summary.endpoints)} HTTP endpoint(s)."
        )
        features = _backend_features(summary)
        goals = [
            "Every endpoint returns the documented status for valid and invalid input.",
            "Protected endpoints reject unauthenticated requests with 401.",
            "Authenticated CRUD flows create, read, update and delete correctly.",
        ]
    else:
        overview = (
            f"{project} is a {', '.join(summary.tech_stack)} web app with "
            f"{len(summary.pages)} page route(s)."
        )
        features = _frontend_features(summary)
        goals = [
            "Users can log in and reach protected pages.",
            "Protected routes redirect unauthenticated visitors to login.",
            "Core CRUD UI flows (create/edit/delete) work end to end.",
        ]
    if summary.auth_flow:
        goals.insert(0, summary.auth_flow)

    return Prd(
        project=project,
        date=date,
        prepared_by="Generated by Suitest",
        product_overview=overview,
        core_goals=goals,
        features=features,
    )


__all__ = ["build_prd"]
