"""M1d-5 — project write endpoint tests (docs/API.md §3.2).

Covers ``POST /projects``, ``PATCH /projects/:id`` (incl. immutable slug +
gating-suite validation), ``DELETE /projects/:id?confirmCascade=...``, and
``POST /projects/:id/restore``. Each test exercises ONE acceptance criterion
from plan-05b — happy paths first, then cross-workspace 404, role-gate 403,
slug autogen, slug collision, gating-suite validation, cascade confirmation,
restore semantics, audit + WS broadcast.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from sqlalchemy import select
from suitest_db.models.audit import AuditLog
from suitest_db.models.case import TestCase
from suitest_db.models.project import Project, Suite
from suitest_shared.domain.enums import CaseSource, Role

if TYPE_CHECKING:
    from api_harness import ApiDb


# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


async def _project(api_db: ApiDb, ws_id: str, *, slug: str = "pw-proj", name: str = "P") -> Project:
    project = Project(workspace_id=ws_id, slug=slug, name=name)
    await api_db.add_all([project])
    return project


async def _suite(api_db: ApiDb, project_id: str, *, name: str = "S") -> Suite:
    suite = Suite(project_id=project_id, name=name, order=0)
    await api_db.add_all([suite])
    return suite


async def _case(api_db: ApiDb, suite_id: str, *, public_id: str) -> TestCase:
    case = TestCase(
        suite_id=suite_id,
        public_id=public_id,
        name=public_id,
        source=CaseSource.MANUAL,
    )
    await api_db.add_all([case])
    return case


# ---------------------------------------------------------------------------
# POST /projects
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_post_project_happy_path(api_db: ApiDb) -> None:
    """201 + project row returned with workspace_id + slug from explicit body."""
    user = await api_db.seed_user(email="pw-create@example.com")
    ws = await api_db.seed_workspace(slug="pw-create-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)

    async with api_db.client(user) as c:
        resp = await c.post(
            "/api/v1/projects",
            json={"name": "Checkout Flow", "slug": "checkout-flow", "description": "demo"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 201, resp.text
    body = resp.json()
    assert body["workspace_id"] == ws.id
    assert body["slug"] == "checkout-flow"
    assert body["name"] == "Checkout Flow"
    assert body["id"]


@pytest.mark.asyncio
async def test_post_project_slug_autogenerated_from_name(api_db: ApiDb) -> None:
    """Omitting slug derives ``"My Login Flow!" -> "my-login-flow"``."""
    user = await api_db.seed_user(email="pw-autoslug@example.com")
    ws = await api_db.seed_workspace(slug="pw-autoslug-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)

    async with api_db.client(user) as c:
        resp = await c.post(
            "/api/v1/projects",
            json={"name": "My Login Flow!"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 201, resp.text
    assert resp.json()["slug"] == "my-login-flow"


@pytest.mark.asyncio
async def test_post_project_slug_uniqueness_within_workspace(api_db: ApiDb) -> None:
    """Re-POSTing the same explicit slug collides → 409 ``DUPLICATE_PROJECT_SLUG``."""
    user = await api_db.seed_user(email="pw-dupe@example.com")
    ws = await api_db.seed_workspace(slug="pw-dupe-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    await _project(api_db, ws.id, slug="dupe-me")

    async with api_db.client(user) as c:
        resp = await c.post(
            "/api/v1/projects",
            json={"name": "Other", "slug": "dupe-me"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 409, resp.text
    envelope = resp.json()["detail"]["error"]
    assert envelope["code"] == "DUPLICATE_PROJECT_SLUG"
    assert envelope["details"]["slug"] == "dupe-me"


@pytest.mark.asyncio
async def test_post_project_slug_cross_workspace_collision_ok(api_db: ApiDb) -> None:
    """Same slug in a *different* workspace is allowed (per-workspace unique)."""
    user = await api_db.seed_user(email="pw-xws-dupe@example.com")
    ws = await api_db.seed_workspace(slug="pw-xws-dupe-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    other = await api_db.seed_workspace(slug="pw-xws-dupe-other", name="Other")
    await _project(api_db, other.id, slug="shared-slug")

    async with api_db.client(user) as c:
        resp = await c.post(
            "/api/v1/projects",
            json={"name": "Mine", "slug": "shared-slug"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 201, resp.text


@pytest.mark.asyncio
async def test_post_project_role_QA_returns_403(api_db: ApiDb) -> None:
    """QA cannot create projects — gate is ADMIN/OWNER only."""
    user = await api_db.seed_user(email="pw-qa-create@example.com")
    ws = await api_db.seed_workspace(slug="pw-qa-create-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.QA)

    async with api_db.client(user) as c:
        resp = await c.post(
            "/api/v1/projects",
            json={"name": "Blocked", "slug": "blocked"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 403


# ---------------------------------------------------------------------------
# PATCH /projects/:id
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_patch_project_metadata_updates_name_description(api_db: ApiDb) -> None:
    """PATCH metadata-only → name + description applied."""
    user = await api_db.seed_user(email="pw-patch@example.com")
    ws = await api_db.seed_workspace(slug="pw-patch-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id, name="orig")

    async with api_db.client(user) as c:
        resp = await c.patch(
            f"/api/v1/projects/{project.id}",
            json={"name": "renamed", "description": "new-desc"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["name"] == "renamed"
    assert body["description"] == "new-desc"


@pytest.mark.asyncio
async def test_patch_project_slug_attempt_returns_400_IMMUTABLE_SLUG(api_db: ApiDb) -> None:
    """Including ``slug`` in PATCH body → 400 ``IMMUTABLE_SLUG``."""
    user = await api_db.seed_user(email="pw-immut@example.com")
    ws = await api_db.seed_workspace(slug="pw-immut-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id, slug="locked-in")

    async with api_db.client(user) as c:
        resp = await c.patch(
            f"/api/v1/projects/{project.id}",
            json={"slug": "renamed-slug"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 400, resp.text
    envelope = resp.json()["detail"]["error"]
    assert envelope["code"] == "IMMUTABLE_SLUG"


@pytest.mark.asyncio
async def test_patch_project_gating_suite_id_valid(api_db: ApiDb) -> None:
    """``gatingSuiteId`` set to an in-project suite → 200, value persisted."""
    user = await api_db.seed_user(email="pw-gating-ok@example.com")
    ws = await api_db.seed_workspace(slug="pw-gating-ok-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id)
    suite = await _suite(api_db, project.id, name="gate")

    async with api_db.client(user) as c:
        resp = await c.patch(
            f"/api/v1/projects/{project.id}",
            json={"gatingSuiteId": suite.id},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 200, resp.text
    assert resp.json()["gating_suite_id"] == suite.id


@pytest.mark.asyncio
async def test_patch_project_gating_suite_id_other_project_returns_400(
    api_db: ApiDb,
) -> None:
    """Suite from another project → 400 ``INVALID_GATING_SUITE`` with both ids."""
    user = await api_db.seed_user(email="pw-gating-bad@example.com")
    ws = await api_db.seed_workspace(slug="pw-gating-bad-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project_a = await _project(api_db, ws.id, slug="proj-a", name="A")
    project_b = await _project(api_db, ws.id, slug="proj-b", name="B")
    foreign_suite = await _suite(api_db, project_b.id, name="b-suite")

    async with api_db.client(user) as c:
        resp = await c.patch(
            f"/api/v1/projects/{project_a.id}",
            json={"gatingSuiteId": foreign_suite.id},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 400, resp.text
    envelope = resp.json()["detail"]["error"]
    assert envelope["code"] == "INVALID_GATING_SUITE"
    assert envelope["details"]["suiteId"] == foreign_suite.id
    assert envelope["details"]["projectId"] == project_a.id


@pytest.mark.asyncio
async def test_patch_project_default_mcp_routing_persists(api_db: ApiDb) -> None:
    """``defaultMcpRouting`` JSONB patch round-trips."""
    user = await api_db.seed_user(email="pw-routing@example.com")
    ws = await api_db.seed_workspace(slug="pw-routing-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id)

    routing = {"FE_WEB": "playwright-mcp", "BE_REST": "api-http-mcp"}
    async with api_db.client(user) as c:
        resp = await c.patch(
            f"/api/v1/projects/{project.id}",
            json={"defaultMcpRouting": routing},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 200, resp.text
    assert resp.json()["default_mcp_routing"] == routing


@pytest.mark.asyncio
async def test_patch_project_cross_workspace_returns_404(api_db: ApiDb) -> None:
    user = await api_db.seed_user(email="pw-xws-patch@example.com")
    ws = await api_db.seed_workspace(slug="pw-xws-patch-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    other = await api_db.seed_workspace(slug="pw-xws-patch-other", name="Other")
    project = await _project(api_db, other.id, slug="other-proj")

    async with api_db.client(user) as c:
        resp = await c.patch(
            f"/api/v1/projects/{project.id}",
            json={"name": "hack"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 404


@pytest.mark.asyncio
async def test_patch_project_role_QA_returns_403(api_db: ApiDb) -> None:
    user = await api_db.seed_user(email="pw-qa-patch@example.com")
    ws = await api_db.seed_workspace(slug="pw-qa-patch-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.QA)
    project = await _project(api_db, ws.id)

    async with api_db.client(user) as c:
        resp = await c.patch(
            f"/api/v1/projects/{project.id}",
            json={"name": "x"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 403


# ---------------------------------------------------------------------------
# DELETE /projects/:id
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_delete_project_without_confirmCascade_returns_409(api_db: ApiDb) -> None:
    """Project with suites + no ``confirmCascade`` → 409 with counts."""
    user = await api_db.seed_user(email="pw-del-409@example.com")
    ws = await api_db.seed_workspace(slug="pw-del-409-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id)
    suite = await _suite(api_db, project.id)
    await _case(api_db, suite.id, public_id="TC-DC1")
    await _case(api_db, suite.id, public_id="TC-DC2")

    async with api_db.client(user) as c:
        resp = await c.delete(
            f"/api/v1/projects/{project.id}",
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 409, resp.text
    envelope = resp.json()["detail"]["error"]
    assert envelope["code"] == "CONFIRM_CASCADE_REQUIRED"
    assert envelope["details"]["suiteCount"] == 1
    assert envelope["details"]["caseCount"] == 2
    assert envelope["details"]["resourceType"] == "project"


@pytest.mark.asyncio
async def test_delete_project_with_confirmCascade_cascade_tombstones(api_db: ApiDb) -> None:
    """``?confirmCascade=true`` cascades project + suites + cases."""
    user = await api_db.seed_user(email="pw-del-cascade@example.com")
    ws = await api_db.seed_workspace(slug="pw-del-cascade-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id)
    suite_a = await _suite(api_db, project.id, name="A")
    suite_b = await _suite(api_db, project.id, name="B")
    case_1 = await _case(api_db, suite_a.id, public_id="TC-CD1")
    case_2 = await _case(api_db, suite_b.id, public_id="TC-CD2")

    async with api_db.client(user) as c:
        resp = await c.delete(
            f"/api/v1/projects/{project.id}?confirmCascade=true",
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 204, resp.text

    async with api_db.maker() as session:
        p = await session.get(Project, project.id)
        sa = await session.get(Suite, suite_a.id)
        sb = await session.get(Suite, suite_b.id)
        c1 = await session.get(TestCase, case_1.id)
        c2 = await session.get(TestCase, case_2.id)
    assert p is not None and p.deleted_at is not None
    assert sa is not None and sa.deleted_at is not None
    assert sb is not None and sb.deleted_at is not None
    assert c1 is not None and c1.deleted_at is not None
    assert c2 is not None and c2.deleted_at is not None


@pytest.mark.asyncio
async def test_delete_project_with_zero_suites_no_confirm_needed(api_db: ApiDb) -> None:
    """Empty project (no suites) → 204 without confirmCascade."""
    user = await api_db.seed_user(email="pw-del-empty@example.com")
    ws = await api_db.seed_workspace(slug="pw-del-empty-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id)

    async with api_db.client(user) as c:
        resp = await c.delete(
            f"/api/v1/projects/{project.id}",
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 204, resp.text


@pytest.mark.asyncio
async def test_delete_project_role_QA_returns_403(api_db: ApiDb) -> None:
    """QA cannot delete projects — gate is ADMIN/OWNER only."""
    user = await api_db.seed_user(email="pw-qa-del@example.com")
    ws = await api_db.seed_workspace(slug="pw-qa-del-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.QA)
    project = await _project(api_db, ws.id)

    async with api_db.client(user) as c:
        resp = await c.delete(
            f"/api/v1/projects/{project.id}?confirmCascade=true",
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 403


@pytest.mark.asyncio
async def test_delete_project_cross_workspace_returns_404(api_db: ApiDb) -> None:
    user = await api_db.seed_user(email="pw-del-xws@example.com")
    ws = await api_db.seed_workspace(slug="pw-del-xws-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    other = await api_db.seed_workspace(slug="pw-del-xws-other", name="Other")
    project = await _project(api_db, other.id, slug="other-del-proj")

    async with api_db.client(user) as c:
        resp = await c.delete(
            f"/api/v1/projects/{project.id}?confirmCascade=true",
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 404


# ---------------------------------------------------------------------------
# POST /projects/:id/restore
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_restore_project_clears_deleted_at_but_not_children(api_db: ApiDb) -> None:
    """Restore flips the project tombstone — suites + cases stay tombstoned."""
    user = await api_db.seed_user(email="pw-restore@example.com")
    ws = await api_db.seed_workspace(slug="pw-restore-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id)
    suite = await _suite(api_db, project.id)
    case = await _case(api_db, suite.id, public_id="TC-RR1")

    async with api_db.client(user) as c:
        del_resp = await c.delete(
            f"/api/v1/projects/{project.id}?confirmCascade=true",
            headers={"X-Workspace-Id": ws.id},
        )
        assert del_resp.status_code == 204

        restore_resp = await c.post(
            f"/api/v1/projects/{project.id}/restore",
            headers={"X-Workspace-Id": ws.id},
        )
    assert restore_resp.status_code == 204, restore_resp.text

    async with api_db.maker() as session:
        p = await session.get(Project, project.id)
        s = await session.get(Suite, suite.id)
        cs = await session.get(TestCase, case.id)
    assert p is not None and p.deleted_at is None
    assert s is not None and s.deleted_at is not None
    assert cs is not None and cs.deleted_at is not None


@pytest.mark.asyncio
async def test_restore_project_idempotent(api_db: ApiDb) -> None:
    """Re-POST after restore returns 204 (idempotent)."""
    user = await api_db.seed_user(email="pw-restore-idem@example.com")
    ws = await api_db.seed_workspace(slug="pw-restore-idem-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id)

    async with api_db.client(user) as c:
        resp = await c.post(
            f"/api/v1/projects/{project.id}/restore",
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 204


@pytest.mark.asyncio
async def test_restore_project_role_QA_returns_403(api_db: ApiDb) -> None:
    user = await api_db.seed_user(email="pw-restore-qa@example.com")
    ws = await api_db.seed_workspace(slug="pw-restore-qa-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.QA)
    project = await _project(api_db, ws.id)

    async with api_db.client(user) as c:
        resp = await c.post(
            f"/api/v1/projects/{project.id}/restore",
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 403


# ---------------------------------------------------------------------------
# LIST excludes deleted
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_list_projects_excludes_deleted(api_db: ApiDb) -> None:
    """``GET /projects`` default-filters ``deleted_at IS NULL``."""
    user = await api_db.seed_user(email="pw-list-act@example.com")
    ws = await api_db.seed_workspace(slug="pw-list-act-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    active = await _project(api_db, ws.id, slug="alive", name="alive")
    dead = await _project(api_db, ws.id, slug="dead", name="dead")

    async with api_db.client(user) as c:
        await c.delete(
            f"/api/v1/projects/{dead.id}",
            headers={"X-Workspace-Id": ws.id},
        )
        resp = await c.get("/api/v1/projects", headers={"X-Workspace-Id": ws.id})
    assert resp.status_code == 200
    ids = {row["id"] for row in resp.json()["items"]}
    assert ids == {active.id}


@pytest.mark.asyncio
async def test_get_deleted_project_returns_404(api_db: ApiDb) -> None:
    """``GET /projects/:id`` on a tombstoned project → 404."""
    user = await api_db.seed_user(email="pw-get-dead@example.com")
    ws = await api_db.seed_workspace(slug="pw-get-dead-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id)

    async with api_db.client(user) as c:
        await c.delete(
            f"/api/v1/projects/{project.id}",
            headers={"X-Workspace-Id": ws.id},
        )
        resp = await c.get(
            f"/api/v1/projects/{project.id}",
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 404


# ---------------------------------------------------------------------------
# Audit log
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_post_project_audit_row_written(api_db: ApiDb) -> None:
    """``project.created`` audit row lands with the workspace + resource id."""
    user = await api_db.seed_user(email="pw-audit-create@example.com")
    ws = await api_db.seed_workspace(slug="pw-audit-create-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)

    async with api_db.client(user) as c:
        resp = await c.post(
            "/api/v1/projects",
            json={"name": "Audited", "slug": "audited"},
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 201
    async with api_db.maker() as session:
        rows = (await session.scalars(select(AuditLog).where(AuditLog.workspace_id == ws.id))).all()
    actions = {r.action for r in rows}
    assert "project.created" in actions


@pytest.mark.asyncio
async def test_delete_project_audit_row_written_with_cascade_ids(api_db: ApiDb) -> None:
    """Cascade delete audits ``project.soft_deleted_with_cascade`` with cascade payload."""
    user = await api_db.seed_user(email="pw-audit-del@example.com")
    ws = await api_db.seed_workspace(slug="pw-audit-del-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)
    project = await _project(api_db, ws.id)
    suite = await _suite(api_db, project.id)
    case = await _case(api_db, suite.id, public_id="TC-AC1")

    async with api_db.client(user) as c:
        resp = await c.delete(
            f"/api/v1/projects/{project.id}?confirmCascade=true",
            headers={"X-Workspace-Id": ws.id},
        )
    assert resp.status_code == 204

    async with api_db.maker() as session:
        rows = (
            await session.scalars(
                select(AuditLog).where(
                    AuditLog.workspace_id == ws.id,
                    AuditLog.action == "project.soft_deleted_with_cascade",
                )
            )
        ).all()
    assert rows
    metadata = rows[0].metadata_json or {}
    assert metadata.get("suiteCount") == 1
    assert metadata.get("caseCount") == 1
    assert suite.id in (metadata.get("cascadedSuiteIds") or [])
    assert case.id in (metadata.get("cascadedCaseIds") or [])


# ---------------------------------------------------------------------------
# WS broadcast
# ---------------------------------------------------------------------------


# mypy: warn_unused_ignores=False
@pytest.mark.asyncio
async def test_post_project_emits_project_created_ws_event(api_db: ApiDb) -> None:
    """A successful create publishes ``project.created`` on ``workspace:<wsId>``."""
    import fakeredis
    import fakeredis.aioredis
    from asgi_lifespan import LifespanManager
    from httpx import ASGITransport, AsyncClient

    user = await api_db.seed_user(email="pw-ws-event@example.com")
    ws = await api_db.seed_workspace(slug="pw-ws-event-ws", name="W")
    await api_db.seed_membership(workspace_id=ws.id, user_id=user.id, role=Role.ADMIN)

    server = fakeredis.FakeServer()
    redis_client = fakeredis.aioredis.FakeRedis(server=server, decode_responses=False)
    received: list[bytes] = []

    app = api_db.app_for(user)
    app.state.ws_redis = redis_client

    pubsub = redis_client.pubsub()
    await pubsub.subscribe(f"workspace:{ws.id}")

    async def _drain() -> None:
        await pubsub.get_message(ignore_subscribe_messages=False, timeout=1.0)
        for _ in range(5):
            msg = await pubsub.get_message(ignore_subscribe_messages=True, timeout=1.0)
            if msg is not None:
                received.append(msg["data"])
                return

    async with LifespanManager(app):
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as c:
            resp = await c.post(
                "/api/v1/projects",
                json={"name": "WS", "slug": "ws-event"},
                headers={"X-Workspace-Id": ws.id},
            )
            assert resp.status_code == 201
            await _drain()

    await pubsub.aclose()  # type: ignore[no-untyped-call]
    await redis_client.aclose()  # type: ignore[no-untyped-call]
    assert received, "WS publish must reach the workspace:<id> channel"
    decoded = received[0].decode()
    assert "project.created" in decoded
