"""Export the FastAPI OpenAPI 3.1 schema to a JSON file.

Used by CI as a drift gate: ``packages/shared/openapi.json`` is the committed
contract, regenerated by this script and diffed against the committed copy on
every PR (see ``.github/workflows/ci.yml``). Drift = PR failure unless the file
is regenerated and committed.

We deliberately use :func:`suitest_api.main.create_app` and call
``app.openapi()`` directly (no :class:`TestClient`, no lifespan). The schema is
metadata-driven and needs only the app's route table — no DB / Redis. This lets
the script run on contributor laptops and CI lint jobs without booting Postgres.

Usage::

    uv run python scripts/export-openapi.py
    uv run python scripts/export-openapi.py /tmp/openapi.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from suitest_api.main import create_app

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_OUTPUT = _REPO_ROOT / "packages" / "shared" / "openapi.json"


def export_openapi(output_path: Path) -> dict[str, Any]:
    """Build the OpenAPI schema and write it to ``output_path``.

    Returns the schema dict so callers (tests) can assert on its contents
    without re-reading the file.
    """
    app = create_app()
    schema: dict[str, Any] = app.openapi()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    # sort_keys + indent=2 + trailing newline => stable byte-for-byte diffs.
    serialized = json.dumps(schema, indent=2, sort_keys=True)
    output_path.write_text(serialized + "\n", encoding="utf-8")
    return schema


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Optional argv[1] = output path."""
    args = sys.argv[1:] if argv is None else argv
    output = Path(args[0]) if args else _DEFAULT_OUTPUT
    export_openapi(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
