{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" (include "suitest.fullname" .))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suitest.fullname" . }}-secret
  labels:
    {{- include "suitest.labels" . | nindent 4 }}
type: Opaque
stringData:
  SUITEST_AUTH_SECRET: {{ randAlphaNum 32 | quote }}
  SUITEST_ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
